baseurl = "http://docs.logit.io/"
languageCode = "en-us"
title = "Logit Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-48517318-1"

[params]
	# General information
	author = "Logit"
	description = "Documentation for hosted ELK provided by logit.io"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/logit-io/hugo"

	version = "0.0.1"
	logo = "favicon.ico"
	favicon = "favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "logit_io"
	github  = "logit-io"


[[menu.main]]
	name   = "Sending Logs"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Security"
	url    = "security/"
	weight = 10

[[menu.main]]
	name   = "FAQ's"
	url    = "faqs/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
